<?php

namespace Tests;

use App\Models\User;
use Faker\Factory;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

	protected function setUp(): void {
		parent::setUp(); // TODO: Change the autogenerated stub
		$this->withoutExceptionHandling();
		$this->user = \factory(User::class)->create();
	}
}
